[workspace]
resolver = "3"
members = [
    "examples/hello-world",
    "examples/article-server",
    "examples/agent-tool",
    "golden-boot",
    "golden-kernel",
    "golden-macros",
    "golden-agent"
]

[workspace.package]
version = "0.1.11"
edition = "2024"
authors = ["HoChienkuo <he-jianguo@qq.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/HoChienkuo/golden"

[workspace.dependencies]
axum = {
    version = "0.8",
    features = ["multipart"]
}
inventory = "0.3"
thiserror = "2"
tokio = {
    version = "1",
    features = [
        "rt-multi-thread",
        "macros",
        "net",
        "signal",
    ]
}
proc-macro2 = "1"
quote = "1"
syn = {
    version = "2",
    features = ["full"]
}
proc-macro-crate = "3"
trybuild = "1"
serde = {
    version = "1",
    features = ["derive"],
}
serde_json = {
    version = "1",
    features = ["raw_value"]
}
validator = {
    version = "0.20",
    features = ["derive"],
}
reqwest = {
    version = "0.12",
    default-features = false,
    features = ["rustls-tls", "stream", "json"] }
futures-core = "0.3"
futures-util = "0.3"
bytes = "1"
async-trait = "0.1"
async-stream = "0.3"
