[workspace]
resolver = "3"
members = ["examples/hello-world", "golden-boot",
    "golden-core",
    "golden-macros"
]

[workspace.package]
version = "0.1.5"
edition = "2024"
authors = ["HoChienkuo <he-jianguo@qq.com>"]

[workspace.dependencies]
axum = "0.8"
inventory = "0.3"
thiserror = "2"
tokio = {
    version = "1",
    features = [
        "rt-multi-thread",
        "macros",
        "net",
        "signal",
    ]
}
proc-macro2 = "1"
quote = "1"
syn = {
    version = "2",
    features = ["full"]
}
proc-macro-crate = "3"
trybuild = "1"
serde = {
    version = "1",
    features = ["derive"],
}
validator = {
    version = "0.20",
    features = ["derive"],
}