use serde::ser::{SerializeMap, Serializer};
use serde::{Deserialize, Serialize};

use super::tool::{FunctionCall, ToolCall};

/// The role of a message, following the OpenAI Chat conventions.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    System,
    User,
    Assistant,
    Tool,
}

/// The content of a message.
///
/// A message content is either a plain string ([`Content::Text`]) or a list of
/// typed parts ([`Content::Parts`]) used for multimodal inputs.
#[derive(Debug, Clone, PartialEq)]
pub enum Content {
    /// Plain text content.
    Text(String),
    /// An ordered list of typed content parts.
    Parts(Vec<ContentPart>),
}

impl Content {
    /// Returns the concatenated text of this content, if any.
    pub fn as_text(&self) -> Option<&str> {
        match self {
            Content::Text(text) => Some(text),
            Content::Parts(parts) => parts.iter().find_map(|part| match part {
                ContentPart::Text { text } => Some(text.as_str()),
                _ => None,
            }),
        }
    }
}

impl From<String> for Content {
    fn from(value: String) -> Self {
        Content::Text(value)
    }
}

impl From<&str> for Content {
    fn from(value: &str) -> Self {
        Content::Text(value.to_string())
    }
}

impl From<Vec<ContentPart>> for Content {
    fn from(value: Vec<ContentPart>) -> Self {
        Content::Parts(value)
    }
}

impl Serialize for Content {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Content::Text(text) => serializer.serialize_str(text),
            Content::Parts(parts) => parts.serialize(serializer),
        }
    }
}

/// A single typed part of a multimodal message.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ContentPart {
    /// A text part.
    Text { text: String },
    /// An image part, referenced by URL.
    ImageUrl { image_url: ImageUrl },
    /// An audio part, provided as base64 data.
    InputAudio { input_audio: InputAudio },
    /// A file part, referenced by id or provided as base64 data.
    File { file: FilePart },
}

impl ContentPart {
    /// Constructs a text part.
    pub fn text(text: impl Into<String>) -> Self {
        ContentPart::Text { text: text.into() }
    }

    /// Constructs an image part from a URL.
    pub fn image_url(url: impl Into<String>) -> Self {
        ContentPart::ImageUrl {
            image_url: ImageUrl {
                url: url.into(),
                detail: None,
            },
        }
    }
}

/// An image content part.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct ImageUrl {
    /// The URL of the image (or a base64 `data:` URI).
    pub url: String,
    /// The level of detail the model should use for the image.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<ImageDetail>,
}

/// The image detail level.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum ImageDetail {
    Auto,
    Low,
    High,
}

/// An audio content part, encoded as base64.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct InputAudio {
    /// The base64-encoded audio data.
    pub data: String,
    /// The audio format, e.g. `wav` or `mp3`.
    pub format: String,
}

/// A file content part.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct FilePart {
    /// The id of an uploaded file to reference.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file_id: Option<String>,
    /// The filename, required when `file_data` is set.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    /// The base64-encoded file data.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file_data: Option<String>,
}

/// A single message in a chat conversation.
#[derive(Debug, Clone, PartialEq)]
pub struct Message {
    /// The role of the message author.
    pub role: Role,
    /// The message content.
    pub content: Content,
    /// An optional participant name.
    pub name: Option<String>,
    /// The tool calls generated by the model (assistant messages).
    pub tool_calls: Option<Vec<ToolCall>>,
    /// The id of the tool call this message responds to (tool messages).
    pub tool_call_id: Option<String>,
    /// The name and arguments of a function the model called.
    #[deprecated(note = "deprecated by OpenAI; use `tool_calls` instead")]
    pub function_call: Option<FunctionCall>,
}

#[allow(deprecated)]
impl Message {
    fn new(role: Role, content: Content) -> Self {
        Self {
            role,
            content,
            name: None,
            tool_calls: None,
            tool_call_id: None,
            function_call: None,
        }
    }

    /// Constructs a system message.
    pub fn system(content: impl Into<String>) -> Self {
        Self::new(Role::System, Content::Text(content.into()))
    }

    /// Constructs a user message.
    pub fn user(content: impl Into<Content>) -> Self {
        Self::new(Role::User, content.into())
    }

    /// Constructs an assistant message.
    pub fn assistant(content: impl Into<String>) -> Self {
        Self::new(Role::Assistant, Content::Text(content.into()))
    }

    /// Constructs a tool message carrying the result of a tool call.
    pub fn tool(tool_call_id: impl Into<String>, content: impl Into<String>) -> Self {
        let mut message = Self::new(Role::Tool, Content::Text(content.into()));
        message.tool_call_id = Some(tool_call_id.into());
        message
    }

    /// Sets the participant name.
    pub fn name(mut self, name: impl Into<String>) -> Self {
        self.name = Some(name.into());
        self
    }

    /// Sets the tool calls produced by the model.
    pub fn tool_calls(mut self, tool_calls: impl IntoIterator<Item = ToolCall>) -> Self {
        self.tool_calls = Some(tool_calls.into_iter().collect());
        self
    }

    /// Sets the id of the tool call this message responds to.
    pub fn tool_call_id(mut self, tool_call_id: impl Into<String>) -> Self {
        self.tool_call_id = Some(tool_call_id.into());
        self
    }
}

#[allow(deprecated)]
impl Serialize for Message {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        let mut len = 2;
        if self.name.is_some() {
            len += 1;
        }
        if self.tool_calls.is_some() {
            len += 1;
        }
        if self.tool_call_id.is_some() {
            len += 1;
        }
        if self.function_call.is_some() {
            len += 1;
        }

        let mut map = serializer.serialize_map(Some(len))?;
        map.serialize_entry("role", &self.role)?;
        map.serialize_entry("content", &self.content)?;
        if let Some(name) = &self.name {
            map.serialize_entry("name", name)?;
        }
        if let Some(tool_calls) = &self.tool_calls {
            map.serialize_entry("tool_calls", tool_calls)?;
        }
        if let Some(tool_call_id) = &self.tool_call_id {
            map.serialize_entry("tool_call_id", tool_call_id)?;
        }
        if let Some(function_call) = &self.function_call {
            map.serialize_entry("function_call", function_call)?;
        }
        map.end()
    }
}
