use serde::Deserialize;

use super::message::Role;
use super::tool::{FunctionCall, ToolCall};

/// A chat completion response body, following the OpenAI Chat Completions schema.
#[derive(Debug, Clone, Deserialize)]
pub struct ChatResponse {
    /// The unique response id.
    pub id: String,
    /// The object type, always "chat.completion".
    pub object: String,
    /// The creation timestamp (Unix seconds).
    pub created: u64,
    /// The model actually used.
    pub model: String,
    /// The completion choices.
    pub choices: Vec<Choice>,
    /// Token usage statistics.
    #[serde(default)]
    pub usage: Option<Usage>,
    /// A fingerprint identifying the system configuration.
    #[serde(default)]
    pub system_fingerprint: Option<String>,
    /// The service tier used to process the request.
    #[serde(default)]
    pub service_tier: Option<String>,
}

/// A single completion choice.
#[derive(Debug, Clone, Deserialize)]
pub struct Choice {
    /// The index of the choice.
    pub index: u32,
    /// The completion message.
    pub message: ResponseMessage,
    /// The reason the completion finished.
    pub finish_reason: Option<String>,
    /// Log probability information for the choice.
    #[serde(default)]
    pub logprobs: Option<ChoiceLogprobs>,
}

impl Choice {
    /// Returns the text content of this choice.
    pub fn text(&self) -> &str {
        self.message.content()
    }
}

/// Log probability information for a completion choice.
#[derive(Debug, Clone, Deserialize)]
pub struct ChoiceLogprobs {
    /// The log probabilities of the output tokens.
    #[serde(default)]
    pub content: Option<Vec<TokenLogprob>>,
    /// The log probabilities of the refusal tokens.
    #[serde(default)]
    pub refusal: Option<Vec<TokenLogprob>>,
}

/// The log probability of a single token and its most likely alternatives.
#[derive(Debug, Clone, Deserialize)]
pub struct TokenLogprob {
    /// The token.
    pub token: String,
    /// The log probability of this token.
    pub logprob: f64,
    /// The raw bytes of the token.
    #[serde(default)]
    pub bytes: Option<Vec<u8>>,
    /// The most likely tokens and their log probabilities at this position.
    #[serde(default)]
    pub top_logprobs: Vec<TopLogprob>,
}

/// A candidate token and its log probability.
#[derive(Debug, Clone, Deserialize)]
pub struct TopLogprob {
    /// The token.
    pub token: String,
    /// The log probability of this token.
    pub logprob: f64,
    /// The raw bytes of the token.
    #[serde(default)]
    pub bytes: Option<Vec<u8>>,
}

/// The message returned in a completion response.
#[derive(Debug, Clone, Deserialize)]
pub struct ResponseMessage {
    /// The role of the message author, always `assistant`.
    pub role: Role,
    /// The message content, if any.
    pub content: Option<String>,
    /// The refusal message generated by the model, if any.
    #[serde(default)]
    pub refusal: Option<String>,
    /// The tool calls generated by the model, if any.
    #[serde(default)]
    pub tool_calls: Option<Vec<ToolCall>>,
    /// Annotations for the message, such as web search citations.
    #[serde(default)]
    pub annotations: Option<Vec<Annotation>>,
    /// Audio output data, if `audio` was requested.
    #[serde(default)]
    pub audio: Option<ResponseAudio>,
    /// The name and arguments of a function the model called.
    #[deprecated(note = "deprecated by OpenAI; use `tool_calls` instead")]
    #[serde(default)]
    pub function_call: Option<FunctionCall>,
}

impl ResponseMessage {
    /// Returns the text content, or an empty string when there is none.
    pub fn content(&self) -> &str {
        self.content.as_deref().unwrap_or("")
    }
}

/// An annotation attached to an assistant message.
#[derive(Debug, Clone, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Annotation {
    /// A citation of a URL, e.g. from the web search tool.
    UrlCitation { url_citation: UrlCitation },
}

/// A citation of a URL.
#[derive(Debug, Clone, Deserialize)]
pub struct UrlCitation {
    /// The index of the first character of the citation in the message.
    pub start_index: u32,
    /// The index of the last character of the citation in the message.
    pub end_index: u32,
    /// The title of the cited resource.
    pub title: String,
    /// The URL of the cited resource.
    pub url: String,
}

/// Audio output data returned with an assistant message.
#[derive(Debug, Clone, Deserialize)]
pub struct ResponseAudio {
    /// The unique id of the audio response.
    pub id: String,
    /// The base64-encoded audio data.
    pub data: String,
    /// The Unix timestamp (seconds) when the audio data expires.
    pub expires_at: u64,
    /// The transcript of the audio.
    pub transcript: String,
}

/// Token usage statistics.
#[derive(Debug, Clone, Deserialize)]
pub struct Usage {
    /// The number of tokens in the prompt.
    pub prompt_tokens: u32,
    /// The number of tokens in the generated completion.
    pub completion_tokens: u32,
    /// The total number of tokens used.
    pub total_tokens: u32,
    /// A breakdown of tokens used in the prompt.
    #[serde(default)]
    pub prompt_tokens_details: Option<PromptTokensDetails>,
    /// A breakdown of tokens used in the completion.
    #[serde(default)]
    pub completion_tokens_details: Option<CompletionTokensDetails>,
}

/// A breakdown of tokens used in the prompt.
#[derive(Debug, Clone, Deserialize)]
pub struct PromptTokensDetails {
    /// Cached tokens present in the prompt.
    #[serde(default)]
    pub cached_tokens: Option<u32>,
    /// Audio input tokens present in the prompt.
    #[serde(default)]
    pub audio_tokens: Option<u32>,
}

/// A breakdown of tokens used in the completion.
#[derive(Debug, Clone, Deserialize)]
pub struct CompletionTokensDetails {
    /// Tokens generated by the model for reasoning.
    #[serde(default)]
    pub reasoning_tokens: Option<u32>,
    /// Audio tokens generated by the model.
    #[serde(default)]
    pub audio_tokens: Option<u32>,
    /// Tokens generated by the model for a prediction that were accepted.
    #[serde(default)]
    pub accepted_prediction_tokens: Option<u32>,
    /// Tokens generated by the model for a prediction that were rejected.
    #[serde(default)]
    pub rejected_prediction_tokens: Option<u32>,
}
