[package]
name = "golden-agent"
version = "0.1.3"
edition.workspace = true
authors.workspace = true
description = "An annotation-driven agent engineering framework for Rust"
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
reqwest.workspace = true
futures-core.workspace = true
futures-util.workspace = true
bytes.workspace = true
async-trait.workspace = true
async-stream.workspace = true
inventory.workspace = true
golden-macros = { path = "../golden-macros", features = ["agent"] }

[[example]]
name = "agent"
path = "examples/agent.rs"

[[example]]
name = "chat_completion"
path = "examples/chat_completion.rs"

[[example]]
name = "chat_stream"
path = "examples/chat_stream.rs"

[[example]]
name = "tools"
path = "examples/tools.rs"
