#![recursion_limit = "256"]

// Paths generated by `#[tool]` use `::golden_agent`, so that they resolve both
// from dependents and from this crate's own examples and tests. The alias keeps
// them working when the macro is used inside this crate itself.
extern crate self as golden_agent;

pub mod agent;
mod error;
pub mod llm;
pub mod tool;

pub use agent::{
    Agent, AgentBuilder, AgentConfig, AgentEvent, AgentResult, AgentState, AgentStream, Middleware,
    ModelHandler, Retry, ToolHandler, ToolSet,
};
pub use error::{ApiErrorBody, ApiErrorDetail, Error};
pub use llm::chat::{
    ChatEvent, ChatModel, ChatRequest, ChatResponse, ChatStream, Content, ContentPart,
    FinishReason, Message, Role, ToolCall, ToolChoice, Usage,
};
pub use llm::{
    AnthropicLlm, AnthropicModel, DeepSeekLlm, DeepSeekModel, HttpConfig, OpenAiLlm, OpenAiModel,
};
pub use tool::{
    FromToolSpec, Tool, ToolDefinition, ToolSpec, registered_tools, render_tools, tool_specs,
};

#[doc(inline)]
pub use golden_macros::tool;

#[doc(hidden)]
pub mod __private {
    pub use crate::tool::ToolDefinition;
    pub use futures_util;
    pub use inventory;
    pub use serde_json;
}
