use serde::Deserialize;
use serde_json::Value;

/// A Messages API response body.
///
/// See <https://platform.claude.com/docs/en/api/messages>.
#[derive(Debug, Clone, Deserialize)]
pub struct MessagesResponse {
    /// The unique message id.
    pub id: String,
    /// The model that produced the message.
    #[serde(default)]
    pub model: String,
    /// Content generated by the model.
    pub content: Vec<OutputBlock>,
    /// Why generation stopped.
    #[serde(default)]
    pub stop_reason: Option<String>,
    /// Billing and rate-limit usage.
    #[serde(default)]
    pub usage: Usage,
}

/// A content block in a response message.
///
/// Only the block types this crate consumes are modeled; every other type
/// (`thinking`, server tool results, ...) deserializes to [`OutputBlock::Other`]
/// and is ignored.
#[derive(Debug, Clone, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum OutputBlock {
    /// Plain text.
    Text {
        /// The text.
        text: String,
    },
    /// A tool invocation requested by the model.
    ToolUse {
        /// The id of the tool use.
        id: String,
        /// The tool name.
        name: String,
        /// The tool input.
        input: Value,
    },
    /// Any other content block type.
    #[serde(other)]
    Other,
}

/// Billing and rate-limit usage.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct Usage {
    /// The number of input tokens.
    #[serde(default)]
    pub input_tokens: u32,
    /// The number of output tokens.
    #[serde(default)]
    pub output_tokens: u32,
}
